# Generated by Django 3.0.4 on 2020-04-18 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('head_shot', models.ImageField(blank=True, upload_to='profil_images')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
